### ISSUE TITLE
generator is not detected by yeoman once globally installed

### ISSUE THREAD

**Issue by jfallaire** [jfallaire/generator-ps-search-ui-sfdc#1]
We've seen some issue with yeoman not detecting the generator after installing it globally `npm i -g generator-ps-search-ui-sfdc` 

We've also tried to install the generator through the yeoman interactive menu, same result.

![image](https://cloud.githubusercontent.com/assets/7849359/23221770/ed4bead4-f8f3-11e6-9688-8f4b0ea7feb4.png)

![image](https://cloud.githubusercontent.com/assets/7849359/23221773/f28ef59a-f8f3-11e6-96e9-7ea8e806e9e0.png)

![image](https://cloud.githubusercontent.com/assets/7849359/23221783/f791538a-f8f3-11e6-8882-93d92a1a4240.png)

![image](https://cloud.githubusercontent.com/assets/7849359/23221803/04d884b4-f8f4-11e6-86a8-f6ab21aea96c.png)

**Comment by jmdrolet** [comment]
we miss directories "generators" and "utils" in the package when we install it globally

**Comment by jmdro** [comment]
Fixed in 0.1.2

**Comment by jmdrolet** [comment]
Fixed in 0.1.2
